### ISSUE TITLE
nsJson plugin is failed to Serialize json file that the file contain empty array value

### ISSUE THREAD

**Issue by Ariel5yang** [idleberg/atom-nsis-plugins#6]
nsJson plugin is failed to Serialize json file that the file contain empty array value, example：
{
 "group": "classes",
 "students": []
 "groupName": "rocket"
}

**Comment by idleberg** [comment]
I'm not sure if you're reporting a problem in one of the snippets or whether there's a bug in the nsJSON plugin? If the latter is true, you'd have to report the problem to the maintainer of the plugin (or on the NSIS forums).

**Comment by idleberg** [comment]
The example above is invalid JSON — there needs to be a comma after the array.
